### PR TITLE
Our People page

### PR DESCRIPTION
**Pull request by adogins**
- Added the necessary cards to the Our People page according to sigma.
- Changed the text appearance according to sigma.
- Added the correct links to the buttons at the bottom of the About page.
- Changed the globals.css sheet to accommodate the new additions.
- Added a Carousel to the Our People page.
- Most changes are commented out until pictures can be added to the appropriate cards.

Our People 1
Our People 2
Our People 3
Our People 4
Our People 5
Our People 6
Our People 7
Our People 8

### CODE REVIEW

**Comment by jayp822** [comment]
Looks good to me

**Review by jayp822 — APPROVED** [review]

**Comment by KelseySt** [comment]
Lgtm 👍

**Comment by jayp822** [comment]
> Lgtm 👍 Edit: we might be trying to add a card flip to give more info on the members and their contributions which might change how we do the cards. This def works for now I think tho

I can work on the card flip there is a really cool library I want to try its called framer motion
https://www.framer.com/motion/

**Comment by nivedhanatarajan7** [comment]
I really like the changes! Since we are planning how to include member info in the website, and I think this page is dependent on having member details, which we will probably receive during the next couple of weeks, we will probably merge this soon.

**Pull request closed without merging**
