### PR TITLE
Set up and apply style tools to project

### PR DESCRIPTION
**Pull request by ggliv**
As titled. Changes are by commit, reviewers can largely ignore 0a00aad (which just applies style fixes to existing files).

This PR shouldn't affect the visual content of the website, just the style of the source code.

### CODE REVIEW

**Comment by jayp822** [comment]
This is a great addition for our code base it will remove unused imports and make the files took nice with the formatting. However I don't know if could remove some stuff that we might actually need line commented out code that will be used later. Can you explain more about how you added this and what potential downsides it might have?

**Comment by ggliv** [comment]
> This is a great addition for our code base it will remove unused imports and make the files took nice with the formatting. However I don't know if could remove some stuff that we might actually need line commented out code that will be used later. Can you explain more about how you added this and what potential downsides it might have?

It's default-config ESLint and Prettier (well, Prettier is configured to enforce semicolons). I don't think it removes comments. Only downside I can think of is that the pre-commit linting hook might be annoying for local development, but that can be skipped with `--no-verify`.

**Comment by nivedhanatarajan7** [comment]
This is a really nice feature! It seems like there are merge conflicts that need to be resolved to merge this. Thank you!

**Comment by ggliv** [comment]
>merge conflicts

Fixed.

**Review by nivedhanatarajan7 — APPROVED** [review]

**Pull request merged**
