### PR TITLE
Contact us page

### PR DESCRIPTION
**Pull request by jayp822**
#57 

Created frontend for contact us page also made the form into a component for others to use. I did not do the backend portion of the form when someone clicks submit since I don't know how you guys want that done. I would use a third party for managing emails. React email and resend together are a good safe and reliable option.  
https://react.email/
https://resend.com/
Also Amazon SES is good if you want full control.
https://aws.amazon.com/ses/

https://github.com/user-attachments/assets/d552e62a-5c4e-4146-ab61-d3fcc59f46df

### CODE REVIEW

**Comment by justinquinnb** [comment]
Forgive my naivete-- can the form's fields not be packaged in an email that is sent to devdogs@uga.edu upon submitting as-is? 

We're currently using MailChimp to handle outbound messages and campaigns. In terms of inbound messages we have nothing set up though as there hasn't been a need. I'm beyond open to the options you've mentioned if it'll integrate better with the site and the others mentioned here think so. Let's see what they think.

Other than that this looks great, you've knocked it out of the park yet again with this!

**Comment by jayp822** [comment]
A third party email service provider or our own email server is required for the transmission of the email. I think Mailchimp can handle inbound messages as well. All we need is a email service provider or SMTP server. Mail servers play a crucial role in the email delivery process. Without them, users would have no way of transferring those messages to and from other mail clients. There are plenty of free services however it requires creating an account and then using the API Key they give so we can use it in our code to handle form submissions. Also the API key should never be posted to the github repo and it should be in a .env.local file. The simplest way I could do it is create a SMTP server, however it would be less secure and rate limited potentially. The fastest way and free way would be to use resend, react mail, and NextJs server components.

**Comment by nivedhanatarajan7** [comment]
The Contact page looks nice and the components look great! There seems to be something happening with positioning and content fitting the page as intended.

On desktop view, the position of the card seems different: 
image
image


In the mobile view, the position also seems to be different: 
image

**Comment by jayp822** [comment]
check the recent commit I pushed, I merged our recent changes into the branch so that might have been it if the globals.css was touched.

**Comment by jayp822** [comment]
@nivedhanatarajan7 nice catch I didn't even check that. The problem was because I made contact page.js main div have h-[100vh] because I was trying to make the footer always stay at the bottom no matter the screen size. If you do flex, flex-col and have the main div's height = 100vh it will always put the footer at the bottom.

**Review by KelseySt — APPROVED** [review]
Lgtm, mobile fixed

**Pull request closed without merging**
