### PR TITLE
Meetings events update

### PR DESCRIPTION
**Pull request by jayp822**
Dont know what to put for the carousel just let me know

https://github.com/user-attachments/assets/eb4730bd-dc6b-4be1-9825-0d81ee2556df

### CODE REVIEW

**Comment by justinquinnb** [comment]
PXL_20240826_215007630-2
PXL_20240916_214721661-2




6_182150-2](https://github.com/user-attachments/assets/57a3b745-9e31-42e6-8665-f86915276c6d)

Please set all of these to crop (trim to set dimensions without stretching or compressing) to the same size.

**Comment by justinquinnb** [comment]
Additionally, please ensure the word Discord links to our server.

https://discord.com/invite/MuyJ4f5xKE
image

**Comment by jayp822** [comment]
image

**Comment by nivedhanatarajan7** [comment]
I think the spacing around the Meetings and Events title can be smaller. The distance between the title and the subtitles for the two sections can be smaller. Thank you!
image

**Comment by justinquinnb** [comment]
Discord link should be underlined and not boldfaced for parity with rest of site. Special events header can be commented out (leave the carousel in for now) since we don't display nor have any special events yet).

**Comment by jayp822** [comment]
image
made it mobile responsive as well

**Comment by nivedhanatarajan7** [comment]
There seems to be some merge conflicts, can you take a look into resolving those? Thank you!

**Comment by nivedhanatarajan7** [comment]
The page looks great! Thank you!

**Review by nivedhanatarajan7 — APPROVED** [review]

**Pull request merged**
